# on Push, Lint, Test, Build, and Deploy

name: CI Chained Pipeline
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4
        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18.x
        -   name: Install dependencies
            run: npm ci

        -   name: Lint
            run: npm run lint

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18.x
        -   name: Install dependencies
            run: npm ci

        -   name: Test
            run: npm run test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18.x
        -   name: Install dependencies
            run: npm ci

        -   name: Build project
            run: npm run build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18.x
        -   name: Install dependencies
            run: npm ci

        -   name: Build project
            run: npm run build

        -   name: Deploy
            run: echo "Deploying to production..."
 
            